import WebSocket from "ws";
import { Telegraf } from "telegraf";

console.log("======================================");
console.log(" Pump.fun Holder Fee Monitor");
console.log("======================================");

const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const HELIUS_API_KEY = process.env.HELIUS_API_KEY;

if (!TELEGRAM_BOT_TOKEN) {
  console.error("❌ Missing TELEGRAM_BOT_TOKEN");
  process.exit(1);
}

if (!HELIUS_API_KEY) {
  console.error("❌ Missing HELIUS_API_KEY");
  process.exit(1);
}

const PUMP_PROGRAM_ID =
  "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P";

const WS_URL =
  `wss://mainnet.helius-rpc.com/?api-key=${HELIUS_API_KEY}`;

const bot = new Telegraf(TELEGRAM_BOT_TOKEN);

/*
 * CA -> Telegram chat IDs
 *
 * Example:
 *
 * 9SLdx... -> Set(123456789)
 */
const watchedMints = new Map();

let ws = null;
let reconnectTimer = null;

/*
 * ============================================================
 * TELEGRAM
 * ============================================================
 */

bot.catch((err) => {
  console.error("Telegram error:", err);
});

bot.command("start", async (ctx) => {
  await ctx.reply(
    "🟢 Bot is online!\n\n" +
    "/watch <CA> - watch a token\n" +
    "/unwatch <CA> - stop watching\n" +
    "/list - show watched tokens\n" +
    "/test - test Telegram"
  );
});

bot.command("test", async (ctx) => {
  await ctx.reply(
    "✅ Telegram is working."
  );
});

bot.command("watch", async (ctx) => {
  const parts = ctx.message.text.trim().split(/\s+/);
  const mint = parts[1];

  if (!mint) {
    await ctx.reply(
      "Usage:\n/watch <CA>"
    );
    return;
  }

  /*
   * Basic Solana address validation.
   */
  if (mint.length < 30 || mint.length > 50) {
    await ctx.reply(
      "❌ That doesn't look like a valid Solana CA."
    );
    return;
  }

  if (!watchedMints.has(mint)) {
    watchedMints.set(
      mint,
      new Set()
    );
  }

  watchedMints
    .get(mint)
    .add(ctx.chat.id);

  console.log("");
  console.log("======================================");
  console.log("👀 WATCH ADDED");
  console.log("Mint:", mint);
  console.log("Chat:", ctx.chat.id);
  console.log("======================================");

  await ctx.reply(
    "✅ Watching:\n\n" +
    mint +
    "\n\n" +
    "I'll notify you when Pump.fun executes " +
    "DistributeFeeToHolders for this CA."
  );
});

bot.command("unwatch", async (ctx) => {
  const parts = ctx.message.text.trim().split(/\s+/);
  const mint = parts[1];

  if (!mint) {
    await ctx.reply(
      "Usage:\n/unwatch <CA>"
    );
    return;
  }

  const chats =
    watchedMints.get(mint);

  if (!chats) {
    await ctx.reply(
      "That CA isn't being watched."
    );
    return;
  }

  chats.delete(ctx.chat.id);

  if (chats.size === 0) {
    watchedMints.delete(mint);
  }

  await ctx.reply(
    "🛑 Stopped watching:\n\n" +
    mint
  );
});

bot.command("list", async (ctx) => {
  if (watchedMints.size === 0) {
    await ctx.reply(
      "No CAs are currently being watched."
    );
    return;
  }

  let text =
    "👀 WATCHED CAs\n\n";

  for (const [mint, chats] of watchedMints) {
    text +=
      mint +
      "\nWatchers: " +
      chats.size +
      "\n\n";
  }

  await ctx.reply(text);
});

/*
 * ============================================================
 * WEBSOCKET
 * ============================================================
 */

function connectWebSocket() {
  console.log("");
  console.log(
    "🔌 Connecting to Helius WebSocket..."
  );

  ws = new WebSocket(WS_URL);

  ws.on("open", () => {
    console.log(
      "✅ Helius WebSocket connected"
    );

    /*
     * Subscribe specifically to transactions/logs
     * generated by Pump.fun.
     *
     * This is the important part.
     */
    const subscription = {
      jsonrpc: "2.0",
      id: 1,
      method: "logsSubscribe",
      params: [
        {
          mentions: [
            PUMP_PROGRAM_ID
          ]
        },
        {
          commitment: "processed"
        }
      ]
    };

    ws.send(
      JSON.stringify(subscription)
    );

    console.log(
      "📡 Subscribed to Pump.fun logs"
    );
    console.log(
      "⚡ Commitment: processed"
    );
  });

  ws.on("message", async (raw) => {
    try {
      const message =
        JSON.parse(raw.toString());

      /*
       * Subscription confirmation.
       */
      if (
        message.result &&
        message.id === 1
      ) {
        console.log(
          "✅ Subscription ID:",
          message.result
        );
        return;
      }

      if (
        message.method !==
        "logsNotification"
      ) {
        return;
      }

      const value =
        message.params?.result?.value;

      if (!value) {
        return;
      }

      if (value.err) {
        return;
      }

      const signature =
        value.signature;

      const logs =
        value.logs || [];

      /*
       * THIS is the exact instruction we confirmed
       * from your Solscan transaction.
       */
      const isHolderDistribution =
        logs.some((log) =>
          log.includes(
            "Instruction: DistributeFeeToHolders"
          )
        );

      if (!isHolderDistribution) {
        return;
      }

      console.log("");
      console.log(
        "======================================"
      );
      console.log(
        "🚨 DISTRIBUTE_FEE_TO_HOLDERS"
      );
      console.log(
        "Signature:",
        signature
      );
      console.log(
        "======================================"
      );

      /*
       * At this point we KNOW a Pump.fun
       * holder-fee distribution happened.
       *
       * Now we need to determine the mint.
       *
       * We use Helius' transaction RPC to fetch
       * the transaction.
       */

      const mint =
        await getMintFromTransaction(
          signature
        );

      if (!mint) {
        console.log(
          "❌ Couldn't determine mint."
        );
        return;
      }

      console.log(
        "🪙 Distribution mint:",
        mint
      );

      /*
       * Is this CA being watched?
       */
      const watchers =
        watchedMints.get(mint);

      if (
        !watchers ||
        watchers.size === 0
      ) {
        console.log(
          "ℹ️ CA isn't being watched."
        );
        return;
      }

      /*
       * Get reward information.
       */
      const distribution =
        await getDistributionInfo(
          signature,
          mint
        );

      /*
       * Notify Telegram.
       */
      let message =
        "🚨 HOLDER FEES DISTRIBUTED\n\n" +
        "🪙 CA:\n" +
        mint +
        "\n\n";

      if (distribution) {
        message +=
          "💰 Total: " +
          distribution.totalSol.toFixed(9) +
          " SOL\n" +
          "👥 Recipients: " +
          distribution.recipients +
          "\n\n";
      }

      message +=
        "⚡ Detected: processed\n\n" +
        "🔗 https://solscan.io/tx/" +
        signature;

      for (
        const chatId of watchers
      ) {
        try {
          await bot.telegram.sendMessage(
            chatId,
            message,
            {
              disable_web_page_preview: true
            }
          );

          console.log(
            "✅ Telegram notification sent"
          );
        } catch (err) {
          console.error(
            "❌ Telegram error:",
            err.message
          );
        }
      }

    } catch (err) {
      console.error(
        "❌ WebSocket message error:",
        err
      );
    }
  });

  ws.on("error", (err) => {
    console.error(
      "❌ WebSocket error:",
      err.message
    );
  });

  ws.on("close", () => {
    console.log(
      "⚠️ Helius WebSocket disconnected"
    );

    if (!reconnectTimer) {
      reconnectTimer =
        setTimeout(() => {
          reconnectTimer = null;
          connectWebSocket();
        }, 2000);
    }
  });
}

/*
 * ============================================================
 * GET TRANSACTION
 * ============================================================
 */

async function heliusRpc(
  method,
  params
) {
  const response =
    await fetch(
      `https://mainnet.helius-rpc.com/?api-key=${HELIUS_API_KEY}`,
      {
        method: "POST",
        headers: {
          "Content-Type":
            "application/json"
        },
        body: JSON.stringify({
          jsonrpc: "2.0",
          id: 1,
          method,
          params
        })
      }
    );

  const data =
    await response.json();

  if (data.error) {
    throw new Error(
      data.error.message
    );
  }

  return data.result;
}

async function getMintFromTransaction(
  signature
) {
  try {
    const tx =
      await heliusRpc(
        "getTransaction",
        [
          signature,
          {
            commitment: "processed",
            maxSupportedTransactionVersion: 0,
            encoding: "jsonParsed"
          }
        ]
      );

    if (!tx) {
      return null;
    }

    /*
     * Pump.fun instruction is in the outer
     * transaction instructions.
     */
    const instructions =
      tx.transaction
        ?.message
        ?.instructions || [];

    for (
      const ix of instructions
    ) {
      if (
        ix.programId ===
        PUMP_PROGRAM_ID
      ) {
        /*
         * Pump.fun instruction account #3
         * is the Mint.
         */
        if (
          ix.accounts &&
          ix.accounts.length >= 3
        ) {
          return ix.accounts[2];
        }
      }
    }

    return null;

  } catch (err) {
    console.error(
      "❌ Mint lookup failed:",
      err.message
    );

    return null;
  }
}

/*
 * ============================================================
 * GET DISTRIBUTION INFO
 * ============================================================
 */

async function getDistributionInfo(
  signature,
  mint
) {
  try {
    const tx =
      await heliusRpc(
        "getTransaction",
        [
          signature,
          {
            commitment: "processed",
            maxSupportedTransactionVersion: 0,
            encoding: "jsonParsed"
          }
        ]
      );

    if (!tx) {
      return null;
    }

    /*
     * Look for the Pump.fun instruction.
     */
    const instructions =
      tx.transaction
        ?.message
        ?.instructions || [];

    let pumpInstruction = null;

    for (
      const ix of instructions
    ) {
      if (
        ix.programId ===
        PUMP_PROGRAM_ID &&
        ix.accounts &&
        ix.accounts.length >= 4
      ) {
        pumpInstruction = ix;
        break;
      }
    }

    if (!pumpInstruction) {
      return null;
    }

    /*
     * Account #4 is the Holder Rewards account.
     */
    const holderRewards =
      pumpInstruction.accounts[3];

    /*
     * Find inner System transfers.
     */
    const inner =
      tx.meta
        ?.innerInstructions || [];

    let totalLamports = 0;
    let recipients = 0;

    for (
      const group of inner
    ) {
      for (
        const ix of
        group.instructions || []
      ) {
        if (!ix.parsed) {
          continue;
        }

        if (
          ix.program === "system" &&
          ix.parsed.type ===
            "transfer"
        ) {
          const info =
            ix.parsed.info;

          if (
            info?.source ===
              holderRewards &&
            info?.lamports
          ) {
            totalLamports +=
              Number(
                info.lamports
              );

            recipients++;
          }
        }
      }
    }

    return {
      totalSol:
        totalLamports /
        1_000_000_000,

      recipients
    };

  } catch (err) {
    console.error(
      "Distribution info error:",
      err.message
    );

    return null;
  }
}

/*
 * ============================================================
 * START
 * ============================================================
 */

bot
  .launch()
  .then(() => {
    console.log("");
    console.log(
      "======================================"
    );
    console.log(
      "✅ TELEGRAM BOT ONLINE"
    );
    console.log(
      "======================================"
    );

    connectWebSocket();
  })
  .catch((err) => {
    console.error(
      "❌ Telegram launch failed:",
      err
    );

    process.exit(1);
  });

process.once(
  "SIGINT",
  () => bot.stop("SIGINT")
);

process.once(
  "SIGTERM",
  () => bot.stop("SIGTERM")
);
